### PR TITLE
Ownership migration/chanes

### PR DESCRIPTION
**Pull request by Xerbo**

### CODE REVIEW

**Comment by Shnatsel** [comment]
Merged. However, when transferring ownership I get an error:

> Xerbo already has a repository in the Shnatsel/furaffinity-dl network

I suppose you need to delete your fork from github first.

**Comment by Xerbo** [comment]
I've deleted my fork, try again.

**Comment by Xerbo** [comment]
Sadly I caught the email too late and was unable to confirm the transfer, could you try transferring again (I wish that there was a working bridge client for protonmail on Linux so I could receive desktop notifications when I get an email).

**Comment by Shnatsel** [comment]
Done

**Pull request merged**
